name: CI
     on:
       pull_request:
         branches: [ main ]
     jobs:
       test:
         runs-on: ubuntu-latest
         services:
           postgres:
             image: postgres:14
             env:
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: postgres
               POSTGRES_DB: taskdb
             ports:
               - 5434:5432
             options: >-
               --health-cmd pg_isready
               --health-interval 10s
               --health-timeout 5s
               --health-retries 5
           docker:
             image: docker:dind
             options: >-
               --privileged
               -v /var/run/docker.sock:/var/run/docker.sock
         steps:
           - uses: actions/checkout@v3
           - name: Set up Go
             uses: actions/setup-go@v4
             with:
               go-version: '1.21'
           - name: Install migrate
             run: |
               curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
               sudo mv migrate /usr/local/bin/migrate
           - name: Run migrations
             run: |
               migrate -path ./db/migration -database "postgresql://postgres:postgres@localhost:5434/taskdb?sslmode=disable" up
           - name: Run tests
             run: go test ./tests/... -v
           - name: Run linter
             run: |
               curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
               golangci-lint run